### ISSUE TITLE
Undeclared dependency on namespace::clean

### ISSUE THREAD

**Issue by andk** [nqounet/p5-json-rpc-spec#3]
As per subject. Grep:

http://search.cpan.org/grep?release=JSON-RPC-Spec-v1.0.4;string=namespace::clean;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/62081198

Overview:

http://matrix.cpantesters.org/?dist=JSON-RPC-Spec%20v1.0.4

HTH&&Thanks,

**Comment by nqounet** [comment]
@andk 
Hi, Thanks for your comment.
I tried to fix.

**Comment by nqounet** [comment]
http://matrix.cpantesters.org/?dist=JSON-RPC-Spec+v1.0.5

Maybe I was able to fix.
@andk :+1:
